env:
  browser: true
  node: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier

plugins:
  # - import
  - react

settings:
  react:
    version: detect

overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      ecmaFeatures:
        jsx: true
      warnOnUnsupportedTypeScriptVersion: false

rules:
  eqeqeq: [error, allow-null]
  prefer-const: error
  no-undef: off
  no-unused-vars: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  "@typescript-eslint/explicit-module-boundary-types": off
